const PROGRESS_STATUS = {
  MISSING: -3,
  MISSED: -2,
  LATE_TURN_IN: -1,
  NOT_TURN_IN: 0,
  COMPLETED: 2,
  TURN_IN: 3,
  GRADED: 4,
  REJECTED: 5,
};

const OPTIONS_STATUS = {
  [PROGRESS_STATUS.MISSING]: 'Missing',
  [PROGRESS_STATUS.MISSED]: 'Missed',
  [PROGRESS_STATUS.TURN_IN]: 'Turned In',
  [PROGRESS_STATUS.LATE_TURN_IN]: 'Turned In (Late)',
};

export { PROGRESS_STATUS, OPTIONS_STATUS };
